const express=require('express');
const router=express.Router();
router.use('/',require('./homepage'));
router.use('/account',require('./account'));
router.use('/cart',require('./cart'));
router.use('/checkout',require('./checkout'));
router.use('/details',require('./account'));
router.use('/gridview',require('./gridview'));
router.use('/listview',require('./listview'));
module.exports=router;