const adminService=require('../services/admin.service');
module.exports=
async(req,res,next)=>{
     Promise.all([
         adminService.getAllcontact(),
        adminService.getAllcategory(),
adminService.getAllcategoryProduct(),
adminService.getSetting(),
adminService.getNews(),
adminService.getBill(),
adminService.getUser(),
                ]).then(([listcontact,listcategory,listcategoryProduct,listsetting,listnews,listbill,listuser])=>{
                      res.locals.listcontact=listcontact;
res.locals.listcategory=listcategory;
res.locals.listcategoryProduct=listcategoryProduct;
res.locals.listsetting=listsetting;    
res.locals.listnews=listnews;
res.locals.listbill=listbill;
res.locals.listuser=listuser;
next();
}).catch((err)=>{
     next(err);
})
}